apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::650732254329:role/eksctl-abn-nodegroup-abn-NodeInstanceRole-x7837DMRfIT3
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - abn-pod-reader
      userarn: arn:aws:iam::650732254329:user/sandeep
      username: sandeep     
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-09T06:09:20Z"
  name: aws-auth
  namespace: kube-system
  uid: 8b722780-7ae1-48f0-a148-34c4947e4f34