apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::650732254329:role/eksctl-abn-nodegroup-abn-NodeInstanceRole-37opcfYXMn0i
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - abn-pod-reader
      userarn: arn:aws:iam::650732254329:user/sandeep
      username: sandeep
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-31T04:25:29Z"
  name: aws-auth
  namespace: kube-system
  uid: 8cc43a95-abaf-4792-a00e-ff69d265ceac 